# Generated by Django 4.1.4 on 2022-12-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbot',
            name='age',
            field=models.IntegerField(verbose_name='Возраст пользователя'),
        ),
    ]
