# Generated by Django 4.1.4 on 2022-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotApi', '0002_alter_usersbot_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbot',
            name='id_files',
            field=models.CharField(default='', max_length=150, verbose_name='ID Файла'),
        ),
        migrations.AddField(
            model_name='usersbot',
            name='surname',
            field=models.CharField(default='', max_length=150, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='age',
            field=models.CharField(default='', max_length=10, verbose_name='Возраст пользователя'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='city',
            field=models.CharField(default='', max_length=150, verbose_name='Город пользователя'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='id_vk',
            field=models.CharField(default='', max_length=255, verbose_name='ID VK пользователя'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='instagram_id',
            field=models.CharField(default='', max_length=255, verbose_name='Instagram пользователя'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Имя пользователя'),
        ),
    ]
